# Generated by Django 4.2.2 on 2023-06-18 11:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web_app", "0002_rename_user_id_address_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="user_id",
            new_name="uuid",
        ),
    ]
