# Generated by Django 4.2.2 on 2023-06-18 12:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web_app", "0003_rename_user_id_user_uuid"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Email",
            new_name="Message",
        ),
    ]
