# Generated by Django 4.2.2 on 2023-06-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_app", "0004_rename_email_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="external_id",
            field=models.IntegerField(default=0),
        ),
    ]
