# Generated by Django 4.2.2 on 2023-06-18 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("web_app", "0005_message_external_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="web_app.user"
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="web_app.address"
            ),
        ),
    ]
