# Generated by Django 4.2.2 on 2023-06-22 11:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_app", "0006_alter_address_user_alter_message_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="expiry_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 22, 11, 38, 56, 877245)
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="expiry_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 22, 11, 38, 56, 861057)
            ),
        ),
    ]
