# Generated by Django 4.2.2 on 2023-06-22 23:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_app", "0007_address_expiry_time_user_expiry_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="expiry_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 22, 23, 4, 46, 796107)
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="expiry_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 22, 23, 4, 46, 785084)
            ),
        ),
    ]
