# Generated by Django 4.2.2 on 2023-06-22 23:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_app", "0008_alter_address_expiry_time_alter_user_expiry_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="expiry_time",
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="user",
            name="expiry_time",
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
